// SPDX-License-Identifier: Apache-2.0

import type { Book, ContentBlock, InlineSpan, StructuralSection } from "@openbook/book-model";
import type { ResolvedImageMetadata } from "./assets/asset-pipeline.js";
import { DEFAULT_PDF_PROFILE } from "./default-profile.js";
import { UnsupportedContentError } from "./types.js";

/**
 * Escapes text for Typst markup mode (not code mode).
 * Preserves Unicode (including Kannada) intact.
 */
export function escapeTypstText(text: string): string {
  return text.replace(/[\\#$*_`~^<>@\[\]{}]/g, (ch) => `\\${ch}`);
}

function quoteTypstString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function serializeInlines(inlines: InlineSpan[]): string {
  return inlines
    .map((span) => {
      switch (span.type) {
        case "text":
          return escapeTypstText(span.text);
        case "emphasis":
          return `#emph[${serializeInlines(span.children)}]`;
        case "strong":
          return `#strong[${serializeInlines(span.children)}]`;
        case "link": {
          const label = serializeInlines(span.children);
          const href = span.href ?? "";
          // Keep visible label; attach sanitized URL as Typst link when absolute http(s)/mailto.
          if (/^(https?:|mailto:)/i.test(href) && !/[\s"'<>]/.test(href)) {
            return `#link(${quoteTypstString(href)})[${label}]`;
          }
          return label;
        }
        default:
          return "";
      }
    })
    .join("");
}

function serializeBlock(
  block: ContentBlock,
  resolvedImages: ReadonlyMap<string, ResolvedImageMetadata>,
): string {
  switch (block.type) {
    case "paragraph":
      return `${serializeInlines(block.inlines)}\n\n`;

    case "heading": {
      const level = Math.max(1, Math.min(6, block.level));
      const depth = "=".repeat(level);
      return `${depth} ${serializeInlines(block.inlines)}\n\n`;
    }

    case "quote":
      return `#quote(block: true)[${serializeInlines(block.inlines)}]\n\n`;

    case "list": {
      const marker = block.ordered ? "+" : "-";
      const items = block.items
        .map((item) => `${marker} ${serializeInlines(item)}`)
        .join("\n");
      return `${items}\n\n`;
    }

    case "image": {
      const resolved = resolvedImages.get(block.assetId);
      if (!resolved) {
        throw new UnsupportedContentError(
          "image",
          block.id,
          `Image block "${block.id}" references unbundled or unresolved asset "${block.assetId}".`,
        );
      }
      const imageCall = `#figure(\n  image(${quoteTypstString(resolved.relativePath)}),\n  caption: [${serializeInlines(block.caption ?? [])}],\n)\n\n`;
      return imageCall;
    }

    default: {
      const b = block as unknown as { type?: string; id?: string };
      throw new UnsupportedContentError(
        b.type ?? "unknown",
        b.id,
        `Unsupported content block of type "${b.type}".`,
      );
    }
  }
}

function serializeSection(
  section: StructuralSection,
  resolvedImages: ReadonlyMap<string, ResolvedImageMetadata>,
  opts: { pagebreakBefore: boolean },
): string {
  const parts: string[] = [];
  if (opts.pagebreakBefore) {
    parts.push("#pagebreak(weak: true)\n\n");
  }
  if (section.title) {
    parts.push(`= ${escapeTypstText(section.title)}\n\n`);
  }
  for (const block of section.blocks ?? []) {
    parts.push(serializeBlock(block, resolvedImages));
  }
  return parts.join("");
}

function collectSections(book: Readonly<Book>): StructuralSection[] {
  return [
    ...(book.frontMatter ?? []),
    ...(book.chapters ?? []),
    ...(book.backMatter ?? []),
  ];
}

/**
 * Maps a canonical Book to declarative Typst markup (Gate 6 first slice).
 */
export function serializeBookToTypst(
  book: Readonly<Book>,
  resolvedImages: ReadonlyMap<string, ResolvedImageMetadata> = new Map(),
): string {
  const language = book.metadata.language || "und";
  const title = book.metadata.title || "Untitled Book";
  const authors = (book.metadata.authors ?? []).join(", ");
  const profile = DEFAULT_PDF_PROFILE;

  const header: string[] = [
    `// Generated by @openbook/pdf (ADR-0013). Do not edit by hand.`,
    `#set document(title: ${quoteTypstString(title)}${authors ? `, author: ${quoteTypstString(authors)}` : ""})`,
    `#set page(paper: ${quoteTypstString(profile.paper)}, margin: (x: ${profile.margin.x}, y: ${profile.margin.y}))`,
    `#set text(font: (${profile.bodyFont.map(quoteTypstString).join(", ")}), size: ${profile.bodyFontSize}, lang: ${quoteTypstString(language)}, fallback: true)`,
    `#set par(justify: true, leading: ${profile.lineHeight}em)`,
    `#show heading: set text(font: (${profile.headingFont.map(quoteTypstString).join(", ")}))`,
    `#set heading(numbering: none)`,
    ``,
    `= ${escapeTypstText(title)}`,
    ``,
  ];

  if (authors) {
    header.push(`#align(center)[${escapeTypstText(authors)}]\n`);
  }
  if (book.metadata.subtitle) {
    header.push(`#align(center)[_${escapeTypstText(book.metadata.subtitle)}_]\n`);
  }
  header.push(`#pagebreak()\n`);

  const sections = collectSections(book);
  const body = sections
    .map((section, index) =>
      serializeSection(section, resolvedImages, { pagebreakBefore: index > 0 }),
    )
    .join("");

  return `${header.join("\n")}\n${body}`;
}
